### ISSUE TITLE
Generate release notes from structured data

### ISSUE THREAD

**Issue by maroshii** [okteto/docs#176]
To be able to automate the [release notes](https://github.com/okteto/docs/blob/main/src/content/enterprise/install/releases.mdx), we need as a first step to render them in place from structured data (json, yaml, etc). This will allow us to more easily update them on a new release with whatever strategy we see fit moving forward.

We could first start with semi-automating a PR into this repo but then move into a more elaborate workflow where we generate the versioned docs automatically via a okteto/app new-release webhook event.

**Comment by maroshii** [comment]
Schema proposed:

```yaml
- version: "1.0.0"
  description: "First stable major release as **markdown**"
  notes: # sections can be anything
    breaking-changes:
      - "chart rename"
    bugfixes:
      - "ingress-nginx upgrade to [v4.2.1](https://github.com/kubernetes/ingress-nginx/issues/8745)"
      - "typos"
    improvements:
      - "soft limits"
      - "fix critical CVEs"
- version: "0.15.1"
...

```
