### ISSUE TITLE
Docker-compose setting resources docs don't match Docker docs

### ISSUE THREAD

**Issue by bwestover** [okteto/docs#319]
Related to community post: https://community.okteto.com/t/how-to-configure-k8s-resources-limits-requests-from-docker-compose-yml/604/3

In this document: https://www.okteto.com/docs/reference/compose/#resources-object-optional

...it shows that I can add a `resources` object directly below a service definition:

```yaml
resources:
  requests:
    cpu: 300m
    memory: 500Mi
  limits:
    cpu: 500m
    memory: 800Mi
```

There a few issues with this:
- According to https://docs.docker.com/compose/compose-file/deploy/#resources I need a `deploy` object, which `resources` should be a child of (e.g. `[my-service].deploy.resources...`)
- In a docker compose file it looks like `requests` should be `reservations`
- `cpu` should be pluralized (e.g. `[my-service].deploy.resources.reservations.cpus`

It would be great if the docs made it clear that the `deploy.resources` would be mapped into the `.spec.containers[].resources` in Kubernetes, and that `reservations` would become `requests` in the process. [^1]

[^1]: Which currently is not actually true, but should be. Related: https://github.com/okteto/okteto/issues/3383

**Comment by mnevadom** [comment]
Add docker-compose config: 

```yaml
deploy: 
      resources:
          limits:
            cpus: "2"
            memory: "5Gi"
          reservations:
            cpus: 11m
            memory: 60Mi
```
