### ISSUE TITLE
Add docker-compose resources configuration

### ISSUE THREAD

**Issue by mnevadom** [okteto/docs#325]
Related to https://github.com/okteto/okteto/issues/3383

We are supporting both `resources` configuration but just showing one of them in the docs. 
We should at to: 

```
resources:
    limits:
      cpu: "2"
      memory: "5Gi"
    requests:
      cpu: 11m
      memory: 60Mi
```

The docker-compose config: 
```
deploy: 
      resources:
          limits:
            cpus: "2"
            memory: "5Gi"
          reservations:
            cpus: 11m
            memory: 60Mi
```
