### ISSUE TITLE
Migrate samples, tutorials and getting started guides to the new `okteto dev` experience

### ISSUE THREAD

**Issue by pchico83** [okteto/docs#4]
Once the Okteto Dev spec is implemented, our samples should have an okteto manifest that says how to build your container image, how to deploy your application, and how to develop in one component. For example, for the hello world samples, it would look like this:

```
build:
   hello-world: .
deploy:
   - kubectl apply -f k8s.yml
 devs:
    hello-world:
      image: okteto/golang:1
      sync:
        - .:/app
      forward:
        - 2345:2345
```
